### ISSUE TITLE
Alle Webform Vorlagen aus der Cosys Integration laden

### ISSUE THREAD

**Issue by lmoesle** [Miragon/digiwf-core#14]
**Beschreibung**

Aus der Cosys Integration sollen alle verfügbaren Webform Vorlagen geladen werden, damit auf dieser Basis eine Vorlage gewählt und für die Erstellung eines Formulars genutzt werden kann.

**Todos**

- [ ] Lokale Umgebung aufsetzen, um Cosys zu verwenden
- [ ] Cosys API Client neu generieren
- [ ] Neuen Integration Endpunkt in der Cosys Integration anlegen, der die Webform Vorlagen bereitstellt
- [ ] Process anpassen

**Comment by lmoesle** [comment]
In #13 habe ich einen ersten Prozess erstellt. Aktuell fehlen noch die Aufrufe von Cosys und Webform, das sollten wir am besten mit dieser Story noch hinzufügen.
