### ISSUE TITLE
[Epic] DoXisign Showcase

### ISSUE THREAD

**Issue by lmoesle** [Miragon/digiwf-core#17]
**Stufe 1**

```[tasklist]
### Tasks
- [ ] https://github.com/Miragon/digiwf-core/issues/11
- [ ] https://github.com/Miragon/digiwf-core/issues/5
- [ ] https://github.com/Miragon/digiwf-core/issues/4
- [ ] https://github.com/Miragon/digiwf-core/issues/18
- [ ] https://github.com/Miragon/digiwf-core/issues/6
```

**Stufe 2**

```[tasklist]
### Tasks
- [ ] https://github.com/Miragon/digiwf-core/issues/13
- [ ] https://github.com/Miragon/digiwf-core/issues/16
- [ ] https://github.com/Miragon/digiwf-core/issues/14
- [ ] https://github.com/Miragon/digiwf-core/issues/15
```
