### ISSUE TITLE
Anpassungen Signing Komponente und Prozess

### ISSUE THREAD

**Issue by lmoesle** [Miragon/digiwf-core#18]
**Beschreibung**

Basierend auf dem erhaltenen Feedback sind Anpassungen an der Signing Komponente sowie eine Optimierung des zugehörigen Prozesses erforderlich. Ziel ist es, die Benutzererfahrung zu verbessern, die Effizienz des Signaturvorgangs zu steigern und sicherzustellen, dass die Komponente reibungslos innerhalb des Gesamtsystems funktioniert. Dieses Ticket dient dazu, die notwendigen Änderungen zu erfassen und umzusetzen.

**Todos**

- [ ] In der Singing Komponente einen Link zum Herunterladen des Dokuments einfügen (Meine Vorgänge)
- [ ] Namen der Formularfelder anpassen
- [ ] Formular in einem Reiter anzeigen
- [ ] Einen Dokument ansehen Button einfügen, nach erfolgreicher Unterschrift
- [ ] Ein Extra Download Formular erstellen
- [ ] Status Dokumente konfigurieren
